Add jasmine recommended rules
infinum/js-linters pull request #56
Opened 2022-02-07 13:20 UTC by thabalija

2022-02-07 13:30 UTC, thabalija commented
I'm thinking about disabling [new-line-before-expect](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/docs/rules/new-line-before-expect.md) rule

2022-02-07 13:34 UTC, fvoska commented
@thabalija I am actually ok with [new-line-before-expect](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/docs/rules/new-line-before-expect.md) because I often see very dense code in tests without any newlines. This will force people to visually separate all three AAA steps of a unit test (Arrange, Act, Assert).

2022-02-07 13:35 UTC, fvoska approved these changes

2022-02-14 08:08 UTC, kristijanbambir requested changes

2022-02-14 08:08 UTC, kristijanbambir commented on packages/eslint-config-angular-ts/package.json
> +    "eslint-plugin-jasmine": "^4.1.3",
Peer dependencies should not have an upper version limit. Here we are preventing projects using this config to install for example eslint-plugin-jasmine v5. This should be changed to >=4 (look at other peer dependencies).

Let's change the dev dependency as well.

2022-04-07 11:28 UTC, kristijanbambir approved these changes

2022-04-07 13:48 UTC, merged